services:
  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile
      args:
        - NONROOT_USERNAME=ubuntu
        - PROJECT_PATH=/project/auth
    restart: on-failure
    # ports:
    #   - "8000"
    environment:
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_REFRESH_SECRET_KEY: ${JWT_REFRESH_SECRET_KEY}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES}
      REFRESH_TOKEN_EXPIRE_DAYS: ${REFRESH_TOKEN_EXPIRE_DAYS}
      JWT_ALGORITHM: ${JWT_ALGORITHM}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE_NAME: ${DB_DATABASE_NAME}
      PROJECT_PATH: /project/auth
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:18-alpine
    restart: on-failure
    # ports:
    #   - "5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      # PGDATA: /var/lib/postgresql/18/docker
    volumes:
      - pg_data:/var/lib/postgresql/18/docker
      - ./db/:/docker-entrypoint-initdb.d/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE_NAME}"]
      interval: 30s
      retries: 5
      start_period: 2s
  chat:
    build:
      context: chat
      target: prod
      dockerfile: Dockerfile
      args:
        - NONROOT_USERNAME=ubuntu
        - PROJECT_PATH=/project/chat
      secrets:
        - HF_TOKEN
        - GIT_AUTH_TOKEN
    # ports:
    #   - "8000"
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE_NAME: ${DB_DATABASE_NAME}
    depends_on:
      db:
        condition: service_healthy
  socket_gateway:
    build:
      context: ./socket_gateway
      dockerfile: Dockerfile
      args:
        - NONROOT_USERNAME=ubuntu
        - PROJECT_PATH=/project/chat
    # Remember nginx.conf expects this on port 5000, so ensure your Dockerfile exposes it.
    # ports:
    #   - "5000"
    # Add other configurations as needed
  # food_detect:
  #   build:
  #     context: ./food_detect
  #     dockerfile: Dockerfile
  #   # Add other configurations as needed
  tts:
    build:
      context: ./tts
      dockerfile: Dockerfile
      args:
        - NONROOT_USERNAME=ubuntu
        - PROJECT_PATH=/project/tts
    # Add other configurations as needed
  redis:
    image: redis:8-alpine
    restart: on-failure
    # ports:
    #   - "6379"
  nginx:
    image: nginx:stable-alpine
    ports:
      - "8100:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - auth
      - db
      - chat
      - socket_gateway
      - redis
volumes:
  pg_data:

secrets:
  HF_TOKEN:
    environment: HF_TOKEN
  GIT_AUTH_TOKEN:
    environment: GIT_AUTH_TOKEN
